[package]
name = "safe-nd"
description = "Safe Network Data Types"
homepage = "https://maidsafe.net"
license = "MIT OR BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/maidsafe/safe-nd"
version = "0.1.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
edition = "2018"
